set_property SRC_FILE_INFO {cfile:/home/pouria/Desktop/codes/FPGA/VIVADO/heichip_1v0/heichip_1v0.srcs/constrs_1/new/template.xdc rfile:../../../heichip_1v0.srcs/constrs_1/new/template.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports trap_0]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/pico_fpga_axi_0_m_axi_WSTRB[0]} {design_1_i/pico_fpga_axi_0_m_axi_WSTRB[1]} {design_1_i/pico_fpga_axi_0_m_axi_WSTRB[2]} {design_1_i/pico_fpga_axi_0_m_axi_WSTRB[3]}]]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/pico_fpga_axi_0_m_axi_RDATA[0]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[1]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[2]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[3]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[4]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[5]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[6]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[7]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[8]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[9]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[10]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[11]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[12]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[13]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[14]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[15]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[16]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[17]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[18]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[19]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[20]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[21]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[22]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[23]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[24]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[25]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[26]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[27]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[28]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[29]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[30]} {design_1_i/pico_fpga_axi_0_m_axi_RDATA[31]}]]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[0]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[1]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[2]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[3]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[4]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[5]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[6]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[7]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[8]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[9]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[10]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[11]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[12]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[13]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[14]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[15]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[16]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[17]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[18]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[19]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[20]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[21]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[22]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[23]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[24]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[25]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[26]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[27]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[28]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[29]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[30]} {design_1_i/pico_fpga_axi_0_m_axi_ARADDR[31]}]]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/pico_fpga_axi_0_m_axi_WDATA[0]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[1]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[2]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[3]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[4]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[5]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[6]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[7]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[8]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[9]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[10]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[11]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[12]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[13]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[14]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[15]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[16]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[17]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[18]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[19]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[20]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[21]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[22]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[23]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[24]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[25]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[26]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[27]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[28]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[29]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[30]} {design_1_i/pico_fpga_axi_0_m_axi_WDATA[31]}]]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
